from psycopg2._psycopg import cursor as Cursor


def update_to_v1_1_0(c: Cursor) -> None:
    c.execute(
        query="""
            CREATE TABLE IF NOT EXISTS coretools_export_updates (
                id INT GENERATED ALWAYS AS IDENTITY,
                uuid BIGINT NOT NULL UNIQUE,
                modify_count INT DEFAULT 0,

                new_measurement BOOLEAN DEFAULT FALSE, -- not really needed, but overwrite all data.
                data_changed BOOLEAN DEFAULT FALSE, -- export previews, export metadata.
                completed BOOLEAN DEFAULT FALSE, -- export raw data
                update_star BOOLEAN DEFAULT FALSE, -- compare with exported metadata.
                update_name BOOLEAN DEFAULT FALSE, -- compare with exported metadata.

                resume_after timestamp DEFAULT '2020-01-01 00:00:00',
                fail_count INT DEFAULT 0,
                PRIMARY KEY(id)
            );
        """
    )

    c.execute(
        query="""
            CREATE INDEX IF NOT EXISTS qdl_export_updates_uuid_index ON coretools_export_updates USING BTREE (uuid);
        """
    )

    c.execute(
        query="""
            CREATE TABLE IF NOT EXISTS coretools_exported (
               id INT GENERATED ALWAYS AS IDENTITY,
               uuid BIGINT NOT NULL UNIQUE,
               path TEXT,
               measurement_start_time timestamp, -- export raw after timeout and not completed.
               raw_final BOOLEAN DEFAULT FALSE, -- Set when completed or after timeout.

               -- export state
               export_state INT DEFAULT 0, -- (0:todo, 1:done, 99: failed),
               export_errors TEXT,

               PRIMARY KEY(id)
            );
        """
    )

    c.execute(
        query="""
            CREATE INDEX IF NOT EXISTS coretools_exported_uuid_index ON coretools_exported USING BTREE (uuid);
        """
    )

    c.execute(
        query="""
            CREATE TABLE IF NOT EXISTS upload_task_queue (
                idx INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                task_iteration INT NOT NULL,
                scope TEXT,
                coretools_uid BIGINT UNIQUE NOT NULL,
                dataset_path TEXT NOT NULL,

                update_dataset BOOLEAN NOT NULL DEFAULT FALSE,
                update_name BOOLEAN NOT NULL DEFAULT FALSE,
                update_rating BOOLEAN NOT NULL DEFAULT FALSE,

                is_ready BOOLEAN NOT NULL DEFAULT FALSE,
                has_failed BOOLEAN NOT NULL DEFAULT FALSE,
                should_retry BOOLEAN NOT NULL DEFAULT FALSE,
                is_claimed_by INT
            );
        """
    )

    c.execute(
        query="""
            CREATE INDEX IF NOT EXISTS task_queue_uid_index ON upload_task_queue (coretools_uid);
            CREATE INDEX IF NOT EXISTS task_queue_is_claimed_by_has_failed_index ON upload_task_queue (is_claimed_by, has_failed);
            CREATE INDEX IF NOT EXISTS task_queue_is_claimed_by_should_retry_index ON upload_task_queue (is_claimed_by, should_retry);
        """
    )

    c.execute(
        query="""
            CREATE TABLE IF NOT EXISTS upload_log (
                idx INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                scope TEXT,
                ct_uid BIGINT NOT NULL,
                upload_timestamp TIMESTAMP NOT NULL,
                message TEXT NOT NULL CHECK (message <> '')
            );
        """
    )

    c.execute(
        query="""
            CREATE INDEX IF NOT EXISTS upload_log_id_index ON upload_log (idx);
        """
    )

    c.execute(
        query="""
            CREATE TABLE IF NOT EXISTS sqdl_dataset (
                idx INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                scope TEXT NOT NULL,
                coretools_uid BIGINT NOT NULL,
                sqdl_uuid UUID NOT NULL
            );
        """
    )

    c.execute(
        query="""
            CREATE INDEX IF NOT EXISTS qdl_dataset_uuid_index ON sqdl_dataset (sqdl_uuid);
        """
    )

    c.execute(
        query="""
            CREATE TABLE IF NOT EXISTS sqdl_file (
                idx INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                dataset_index INT REFERENCES sqdl_dataset (idx),
                sqdl_uuid UUID UNIQUE NOT NULL,
                filename TEXT NOT NULL,
                last_modified BIGINT NOT NULL
            );
        """
    )

    c.execute(
        query="""
            CREATE INDEX IF NOT EXISTS qdl_file_dataset_id_index ON sqdl_file (dataset_index);
            CREATE INDEX IF NOT EXISTS qdl_file_dataset_uuid_index ON sqdl_file (sqdl_uuid);
        """
    )

    c.execute(
        query="""
            CREATE TABLE IF NOT EXISTS database_version (
                major SMALLINT UNIQUE NOT NULL,
                minor SMALLINT UNIQUE NOT NULL,
                patch SMALLINT UNIQUE NOT NULL
            );
        """
    )

    c.execute(
        query="""
            INSERT INTO database_version (
                major, minor, patch
            ) VALUES (
                1, 1, 0
            )
        """
    )

    c.execute(
        # REVIEW SdS: I think sample_info_overview.scope is never used.
        query="""
            ALTER TABLE global_measurement_overview ADD COLUMN IF NOT EXISTS scope TEXT DEFAULT NULL;
            ALTER TABLE sample_info_overview ADD COLUMN IF NOT EXISTS scope TEXT DEFAULT NULL;
        """
    )
