# selection used in databrowser. Any is an allowed value here.
setup: CoreTools
project: Demo
sample: MagicSample

remote_database:
    user: username
    password: yyyyy!
    database: veldhorst_data
    address: vanvliet.qutech.tudelft.nl:5432

databrowser:
    datasource: remote # required value

