# selection used in databrowser. Any is an allowed value here.
setup: CoreTools
project: Demo
sample: MagicSample

# local database can be used for caching of data
local_database:
    user: username
    password: XXXX
    database: measurement_data

remote_database:
    user: username
    password: yyyyy!
    database: veldhorst_data
    address: vanvliet.qutech.tudelft.nl:5432

databrowser:
    datasource: remote # required value
    live_plotting: False

